# -*- coding: utf-8 -*-
"""Test_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jrc52Co53_Iupbo8x0hcAUHoUjxGbGGB
"""

import requests


ngrok_url = "https://f3cf-36-255-255-163.ngrok-free.app/"
endpoint = f"{ngrok_url}/summarize"

text = """
ABSOLUTE SALE DEED

This Deed of Absolute Sale is made and executed on this Fourteenth Day of April, Two Thousand. & Twenty (14-04-2020) at Bangalore:

BY:

Sri. M.R. JAYA RAM, Aged about 66 Years, S/o. Late. M. Rangaswamy, Residing at No.107, 4th Main Road, 4th Phase, 7th Block, BSK 3rd Stage, Bangalore-560085.

PAN-BAUPJ5767N
Herein after called the 'VENDOR' (which term unless repugnant to the context shall mean and include his heirs, administrators, legal representatives, executors & assigns etc.) of the one part.

IN FAVOUR OF:

Sri. GURUPRASADA. S,

Aged about 40 Years, S/o. Late Sreenivasa Rao P.R, Residing at No.30, 1" Floor, Ashirwada, Police Station Road, Basavanagudi, Bangalore-560004.

ΡΑΝ - ΑΕΚPG9454N
Herein after called the 'PURCHASER' (which term unless repugnant to the context shall mean and include his heirs, administrators, legal representatives, executors & assigns etc.) of the other part.

WHEREAS the VENDOR is the sole and absolute owner in possession of the immovable residential property bearing BDA Site No. 107, situated at BSK 3d Stage, 7th Block, 4h Phase, 4th Main, Bangalore, presently within the limits of Bruhat Bangalore Mahanagara Palike Ward No.56, presently property bearing Municipal No.107, PID No.56-196-107, measuring on East to West: 12.19 Metres and North to South: 9.14 Metres, in all measuring 111.41 Square Metres, which is more-fully described in the SCHEDULE hereunder and herein referred to as the "SCHEDULE PROPERTY".
WHEREAS the residential site in which house as described on "SCHEDULE PROPERTY" is present, originally belonged to Bangalore Development Authority (referred to as BDA) and the said Authority has allotted the same in favour of VENDOR vide Allotment Letter dated 28.10.1986 and the VENDOR after having paid the necessary site value BDA has executed Lease Cum Sale Agreement in favour of the VENDOR, vide Document No.2778/1987-88, of Book-1, Volume SF 274, Pages 48 to 52, dated 04.12.1987, registered in the office of the Sub-Registrar, Basavanagudi, Bangalore. The Bangalore Development Authority has delivered the possession of the "SCHEDULE PROPERTY" to the VENDOR and issued Possession Certificate vide PR No.392:1987-88 SL.No.6781, dated 18.12.1987.

WHEREAS after fulfillment of the conditions of the Lease-cum-Sale Agreement, the Bangalore Development Authority has executed Absolute Sale Deed in favour of the VENDOR, vide Document NBDA-1-06273-2007-08 of Book-1, stored in C.D No.BDAD134, dated 05.11.2007, registered in the office of the Additional District Registrar, Bangalore Development Authority, Bangalore.
WHEREAS the "SCHEDULE PROPERTY" presently coming under the revenue jurisdiction of Bruhat Bangalore Mahanagara Palike (BBMP) Ward No.56, the VENDOR's name was mutated in the BBMP records. The VENDOR has paid necessary taxes from the date of purchase till date.

WHEREAS the VENDOR has constructed residential building as per building Sanction Plans from BBMP vide L.P No.344/1990-91 and BBMP vide L.P No.1162/2002-03 and constructed ground floor & first floor RCC Roofed House with total built up area of 2250 Sq.Ft.

WHEREAS the VENDOR is the Absolute Owner in possession of the "SCHEDULE PROPERTY" without any hindrance from anybody from the date of allotment till date. Thus the VENDOR is having full right, title, interest & claim over the same. And is fully seized and possessed of the said property with full power of enjoyment and alienation.

WHEREAS the VENDOR is in need of funds for family requirements, offered to sell the "SCHEDULE PROPERTY" by making following representations:-

a. That the VENDOR is the absolute owner of the "SCHEDULE PROPERTY" and his title thereto is good, marketable and subsisting & that none else have any right, title, interest or share therein,
b. That there is no encumbrance & the "SCHEDULE PROPERTY" is free from attachment, Court or acquisition Proceedings or charges of any kind;

NOW THEREFORE THIS DEED OF SALE WITNESSES That in pursuance of the above & in consideration of sale value of Rs.1,45,00,000/- (Rupees One Crore Forty Five Lakhs Only) paid by the PURCHASER unto the VENDOR the following manner:-
a. Rs.5,00,000/- (Rupees Five Lakhs Only) paid by the PURCHASER to the VENDOR by Cheque bearing No.046313 dated 22.8.2019, drawn on Citi Bank, M.G. Road Branch, Bangalore, as earnest money;

b. Rs.29,80,000/- (Rupees Twenty Nine Lakhs Eighty Thousand Only) as part payment to the VENDOR by way of RTGS bearing Ref No:CITIH16242880393, dated 28-09-2019, from Citi Bank, Jayanagar Branch, Bangalore.

c. Rs.1,08,75,000/- (Rupees One Crore Eight Lakhs Seventy Five Thousand only) vide Demand draft bearing No. 008464, dated 09.04.2020, drawn on IDBI Bank, Mission Road Branch, Bangalore, issued by IDBI Bank, Mission Road Branch, Bangalore, being the proceeds of Housing Loan sanctioned to the PURCHASER, favoring the Account No.10101016546, in the name of VENDOR, in The Bangalore Credit Co-operative Bank Ltd, Chamrajapet, Bangalore;

d. Rs.1,45,000/- (Rupees One Lakh Forty Five Thousand Only) being the 1% of sale value as Tax Deducted at Source payable to Income Tax Department as per Rules, paid by the PURCHASER in two installments vide Challan bearing No.00143, Ref No.IKC2840709, SBM, Basavanagudi dated 28.09.2019 for a sum of Rs.36,250/- (E-Acknowledgement No.AD3713905) & Challan bearing No.00251, Ref No.IKC3570650, SBM, Basavanagudi dated 30.09.2020 for a sum of Rs.1,08,750/- (E-Acknowledgement No. AD3928212)
The VENDOR acknowledges the receipt of the same and states that he has received the entire sale consideration from the PURCHASER in full and final settlement and no amount is due to him.

The VENDOR further hereby admits, acknowledges, acquits and releases the PURCHASER from payment and in consideration thereof. The VENDOR hereby grant, convey, sell, transfer, assign and assure UNTO AND TO THE use of the PURCHASER all that schedule property, free from all encumbrances whatsoever, together with all rights, privileges, appurtenances, advantages whatsoever pertaining to or belonging to the schedule property, viz., immovable property being bearing No. BDA Site No.107, situated at BSK 3rd Stage, 7th Block, 4th Phase, 4th Main, Bangalore, Municipal No.107, PID No.56-196-107, measuring to an extent of 111.41 Square Metres, together with residential structure thereon measuring 2250 Sq.Ft., which shall hold, possess use and enjoy all the right, title and interest, privileges belonging thereto TO HAVE AND TO HOLD & every part thereof UNTO and to the use of the PURCHASER absolutely & forever & further declare that the PURCHASER shall henceforth be the Absolute Owner of the "SCHEDULE PROPERTY".WHEREAS the VENDOR do hereby covenant with the PURCHASER that he has good right, title and interest to grant, convey and transfer the "SCHEDULE PROPERTY"& every part thereof unto to the PURCHASER in the manner aforesaid

WHEREAS the VENDOR has not done or knowing suffered or been a party or privy to anything whereby his right to convey the "SCHEDULE PROPERTY" or any part thereof is or may be impeached or affected in title, estate or otherwise or whereby the VENDOR is in any way hindered from selling or conveying the "SCHEDULE PROPERTY" to the PURCHASER absolutely in the manner aforesaid.

Whereas the VENDOR does hereby further covenant with the PURCHASER that the PURCHASER shall at all times hereafter peaceably and quietly enter into, possess and enjoy the "SCHEDULE PROPERTY" now transferred, assigned and sold through this Deed and receive the rents and profits thereof without any interruption or disturbance whatsoever by the VENDOR or by any person/s claiming through or in trust for him or through whom he derived title.

WHEREAS that the VENDOR shall indemnify the PURCHASER against all encumbrances, Charges, Tclaims, demands, legal proceedings and attachment created, occasioned of made by the VENDOR and against all losses damages, cost and expenses which the PURCHASER may suffer, sustain or incur by reason of any such claim, demand or legal proceedings.
WHEREAS the VENDOR further covenants with the PURCHASER that the VENDOR and all the persons lawfully or equitably claiming under the VENDOR, shall and will from time to time and at all times hereafter at the cost of the PURCHASER do, execute and register and cause to be done, executed and registered all such acts, deeds and things for further and more fully & perfectly assuring the "SCHEDULE PROPERTY" & every part thereof TO & UNTO the PURCHASER as shall or may be required by the PURCHASER.

WHEREAS the VENDOR further agrees to indemnify the PURCHASER against any loss or damage that may arise by reason of any claim or defect in or want of title on the part of the VENDOR or any person claiming to be legally or equitably interested in the "SCHEDULE PROPERTY" hereby sold and conveyed or by breach of any of the covenants or conditions herein contained.

That upon the request of the PURCHASER, the VENDOR shall endeavor to get all lawful acts, deeds and things from BDA, or any other person/s, that may be necessary for strengthening the ownership of the "SCHEDULE PROPERTY" in favour of the PURCHASER, if needed.

WHEREAS the VENDOR has delivered actual, physical & vacant Possession of the "SCHEDULE PROPERTY" to the PURCHASER on execution of these presents.

WHEREAS further the VENDOR has delivered all the Original Documents of Title relating to the "SCHEDULE PROPERTY" to the PURCHASER and the
PURCHASER is entitled to get the Khata transferred into his name in the records of BBMP, BWSSB & BESCOM.

The Stamp Duty & Registration Fee has been paid by the PURCHASER in entirety.

SCHEDULE PROPERTY

All that piece and parcel of immovable property bearing No. 107, (PID No.56-196-107), situated at BSK 3rd Stage, 7th Block, 4th Phase, 4th Min, Bangalore, presently within the limits of Bruhat Bangalore Mahanagara Palike, Ward No.56, measuring on East to West: 12.19 Metres and North to South:9.14 Metres, in all measuring 111.41 Square Metres, together with residential structure thereon measuring 2250 sq ft on ground & first floor having mosaic flooring, jungle wood doors and windows with all civic amenities together with all rights, privileges appurtenant thereto and bounded on the:

East by: 30 Feet Road

West by: Site No.103

North by: Site No.108

South by: Site No.106
IN WITNESS WHEREOF THE PARTIES HERETO HAVE HEREUNTO SET THEIR HANDS AND SUBSCRIBED THEIR SIGNATURES TO THIS DEED OF SALE ON THE DAY, MONTH AND THE YEAR FIRST ABOVE MENTIONED BEFORE THE FOLLOWING WITNESSES:-

CONSENTING WITNESS

(SMT. N. CHANDRA PRABHA)

Wife of M.R JAYA RAM

WITNESSES:-
1.

Find in document

Q

(M.R. JAYA RAM)

VENDOR

2.

(GURUPRASADA. S)

PURCHASER

Drafted by

ADVOCATES"""

payload = {
    "text": text,
    "model": "qwen3"
}

response = requests.post(endpoint, json=payload)

print("Status code:", response.status_code)
print("\nResponse:\n", response.json())